# Generated by Django 5.2.4 on 2025-08-04 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_email_verified_user_first_login_otp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='college_name',
            new_name='institute_name',
        ),
    ]
