# Generated by Django 5.2.4 on 2025-08-04 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_college_name_user_institute_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='video_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
