# Generated by Django 5.1.4 on 2025-08-20 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='team_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
